# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.0.8
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: segope44@gmail.com
author_name: netflams10
cloud_provider: none
preset_name: production
project_name: crowd-fund-frontend

