# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.0.12
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: segope44@gmail.com
author_name: netflams10
cloud_provider: none
contract_name: CrowdFund
preset_name: production
project_name: crowd-fund

